import { Controller, Get, Post, Query, Body, HttpCode, HttpStatus } from '@nestjs/common';
import { chatHistoryData, imageData, generatedImageData } from '../mock-data/aiData';

@Controller('ai')
export class AiController {
  @Post('chat')
  @HttpCode(HttpStatus.OK)
  async chat(@Body() body: any) {
    const { prompt } = body;
    const userPrompt = (prompt || '').toLowerCase();

    const responseContents = {
      regular: [
        `This is a mock response designed to simulate an AI-generated reply. Please note that this response is not generated by an actual AI model. You can include 'title', 'code', 'list' keywords in your prompt to get different kinds of mock responses.`,
        `You are seeing a mock response for demonstration purposes. This message is not generated by a real AI model, but rather pre-written for this demo. You can include 'title', 'code', 'list' keywords in your prompt to get different kinds of mock responses.`,
        `For demo purposes, this response is a mock message. It showcases what a typical AI reply might look like, but it is not produced by a real AI. You can include 'title', 'code', 'list' keywords in your prompt to get different kinds of mock responses.`,
        `This mock response is part of a demonstration and is not generated by an actual AI. The content here is pre-defined for showcasing purposes. You can include 'title', 'code', 'list' keywords in your prompt to get different kinds of mock responses.`,
        `As part of this demo, you are viewing a mock response. This text is not created by an AI model, but rather a pre-written example to illustrate functionality. You can include 'title', 'code', 'list' keywords in your prompt to get different kinds of mock responses.`,
      ],
      title: `This is a mock response with a title.

###### Example Title

Please note that this is not generated by an actual AI model.`,
      code: `This is a mock response with a code snippet.

\`\`\`
function example() {
    console.log('This is a mock code snippet.');
}
\`\`\`

Please note that this is not generated by an actual AI model.`,
      list: `This is a mock response with a list.

1. First item
2. Second item
3. Third item

Please note that this is not generated by an actual AI model.`,
    };

    let content =
      responseContents.regular[
        Math.floor(Math.random() * responseContents.regular.length)
      ];

    if (userPrompt.includes('title')) {
      content = responseContents.title;
    }
    if (userPrompt.includes('code')) {
      content = responseContents.code;
    }
    if (userPrompt.includes('list')) {
      content = responseContents.list;
    }

    const response = {
      id: `ai-conversation-${Math.random().toString(36).substr(2, 9)}`,
      choices: [
        {
          finish_reason: 'stop',
          index: 0,
          message: {
            content: content,
            role: 'assistant',
          },
        },
      ],
      created: Math.floor(Date.now() / 1000),
      model: 'gpt-4',
    };

    // Simulate short network delay
    await new Promise((resolve) => setTimeout(resolve, 200));

    return response;
  }

  @Get('chat/history')
  getChatHistory() {
    return chatHistoryData;
  }

  @Get('images')
  getImages(
    @Query('index') index = '1',
    @Query('itemCount') itemCount = '4',
  ) {
    const idx = parseInt(index);
    const count = parseInt(itemCount);
    let loadable = true;
    const offset = (idx - 1) * count;

    let images = imageData;
    if (offset >= images.length) {
      loadable = false;
    }
    images = images.slice(offset, idx * count);

    return {
      data: images,
      loadable,
    };
  }

  @Post('images')
  @HttpCode(HttpStatus.OK)
  async postImages(@Body() body: any) {
    const { prompt } = body;
    const randomSet = generatedImageData[
      Math.floor(Math.random() * generatedImageData.length)
    ];

    const imageSet = randomSet.map((img) => {
      const cloned = { ...img };
      cloned.prompt = prompt;
      return cloned;
    });

    await new Promise((resolve) => setTimeout(resolve, 200));

    return imageSet;
  }
}
